<a href="https://colab.research.google.com/github/Githubmany/Projects/blob/master/GMArtificial_Neural_Network.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Artificial Neural Network

### Importing the libraries

In [ ]:
import numpy as np
import pandas as pd
import tensorflow as tf



In [11]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [12]:
tf.__version__

'2.15.0'

## Part 1 - Data Preprocessing

### Importing the dataset

In [13]:
dataset = pd.read_excel('Folds5x2_pp.xlsx')
X = dataset.iloc[:,:-1].values
y = dataset.iloc[:, -1].values
print(X)
print(y)

[[  14.96   41.76 1024.07   73.17]
 [  25.18   62.96 1020.04   59.08]
 [   5.11   39.4  1012.16   92.14]
 ...
 [  31.32   74.33 1012.92   36.48]
 [  24.48   69.45 1013.86   62.39]
 [  21.6    62.52 1017.23   67.87]]
[463.26 444.37 488.56 ... 429.57 435.74 453.28]


### Splitting the dataset into the Training set and Test set

## Part 2 - Building the ANN

### Initializing the ANN

In [15]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [16]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the second hidden layer

In [17]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the output layer

In [19]:
ann.add(tf.keras.layers.Dense(units=1))

## Part 3 - Training the ANN

### Compiling the ANN

In [20]:
ann.compile(optimizer = 'adam', loss = 'mean_squared_error')

### Training the ANN model on the Training set

In [21]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
240/240 [==============================] - 2s 4ms/step - loss: 222134.6719
Epoch 2/100
240/240 [==============================] - 1s 4ms/step - loss: 12554.6377
Epoch 3/100
240/240 [==============================] - 1s 4ms/step - loss: 374.3930
Epoch 4/100
240/240 [==============================] - 1s 4ms/step - loss: 369.1346
Epoch 5/100
240/240 [==============================] - 1s 3ms/step - loss: 325.7171
Epoch 6/100
240/240 [==============================] - 1s 2ms/step - loss: 268.2850
Epoch 7/100
240/240 [==============================] - 1s 2ms/step - loss: 258.4122
Epoch 8/100
240/240 [==============================] - 1s 2ms/step - loss: 248.0964
Epoch 9/100
240/240 [==============================] - 1s 2ms/step - loss: 233.7659
Epoch 10/100
240/240 [==============================] - 1s 2ms/step - loss: 216.4900
Epoch 11/100
240/240 [==============================] - 0s 2ms/step - loss: 191.0487
Epoch 12/100
240/240 [==============================] - 0s 2ms/step -

### Predicting the results of the Test set

In [22]:
y_pred = ann.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

60/60 [==============================] - 0s 1ms/step
[[431.99 431.23]
 [463.08 460.01]
 [466.59 461.14]
 ...
 [473.81 473.26]
 [440.62 438.  ]
 [459.82 463.28]]
